### ISSUE TITLE
Liferay JS Adapt task doesn't work with v2.18.2 of devDependencies

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-toolkit#546]
1. Download create-react-app project: https://github.com/liferay/liferay-docs/tree/master/en/developer/appdev/code/react-guestbook/before/my-react-guestbook-app
2. Run `yo liferay-js:adapt` and answer prompts (no to server to manually deploy to Docker container)
3. Run `npm run build:liferay` to generate JAR

Expected: JAR file is complete with React code
Actual: JAR file doesn't contain React code

Note: Changing the devDependencies to v2.13.3, re-running `npm install`, and rebuilding the JAR works.

```
  "devDependencies": {
    "liferay-npm-build-support": "2.13.3",
    "liferay-npm-bundler": "2.13.3",
    "liferay-npm-bundler-preset-create-react-app": "2.13.3"
  },
```

**Comment by izaera** [comment]
This should be working as of this [commit](https://github.com/liferay/liferay-js-toolkit/commit/65f7837fdbbad630645c4cfc67a435c69a120825) fixing #512 .

It is not working because of that fix itself, but because I have run a full `deploy:liferay` on a newly created react-app and it has worked.

**Comment by mwilliams2014** [comment]
@izaera I tested the updates locally in my `npm_modules` folder and it's still not working for me. It could be that my app is too out of date with it's package versions. I'll try the deploy command. Did you test with just the `build:liferay` folder? I wouldn't expect that anything would be different between the build and deploy task (since I'm assuming the build task is run during the deploy task) but just figured I would mention it.

**Comment by izaera** [comment]
They are the same, yes. Deploy relies on build to do its task and then just copies the file.

I don't know what could be the cause, it worked flawlessly for me. Maybe upload your project sources in a ZIP file and I'll try to reproduce the error...

**Comment by mwilliams2014** [comment]
It in the repo linked above @izaera : https://github.com/liferay/liferay-docs/tree/master/en/developer/appdev/code/react-guestbook/before/my-react-guestbook-app Please let me know what you find. Perhaps it is just a Docker issue.

**Comment by mwilliams2014** [comment]
Note that the latest versions work for a newly generated React app with sample code...
